# Generated by Django 5.2.1 on 2025-05-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoRevit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheetnumber', models.CharField(max_length=100)),
                ('sheetname', models.CharField(max_length=100)),
                ('viewsubgroup', models.CharField(max_length=100)),
                ('buildingzone', models.CharField(max_length=100)),
            ],
        ),
    ]
